### ISSUE TITLE
Move attestation formats to separate package?

### ISSUE THREAD

**Issue by AGWA** [koesie10/webauthn#10]
Hi!  Thanks for making `github.com/koesie10/webauthn`.

Currently, the only reason to depend on `gopkg.in/square/go-jose.v2` is to support Android SafetyNet Attestation Statements.   Since some folks don't care about attestation, would you be open to moving the code for attestation formats (`attestation_android_safetynet.go`, `attestation_fido.go`, and `attestation_packed.go`) to a separate package?  People who want attestation support could import this package from `package main` with a blank identifier (similar to how SQL drivers are registered).  Then the people who don't want attestation wouldn't need dependencies like `gopkg.in/square/go-jose.v2`.

**Comment by koesie10** [comment]
Sorry about the lack of response. I've now moved all attestation statement formats to separate packages, so you can now only import what attestation formats you need.
